### PR TITLE
Ignore Exceptions, but log them

### PR DESCRIPTION
**Pull request by grofoli**
Added exceptionIgnored to the ConditionEvaluationListener to have the information that these exceptions occured.
* https://github.com/awaitility/awaitility/issues/92

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks again @grofoli. I just like to know the thinking behind calling the ignored exception "trace"? While I don't necessarily thinks it's bad, could it perhaps be even easier to understand if it was just called "ignoredException"? That would lead to a clash with the "IgnoredException" container that is passed to `exceptionIgnored` though so maybe just calling it "exception" or "throwable" might be another idea? WDYT?

**Comment by grofoli** [comment]
@johanhaleby thanks for your feedback! The term "trace" was something I just continued to use and it was not introduced by me. I also used "trace" in the `IgnoredException` container so that the code is consistent. What's your opinion about the following suggestion?
- Rename trace to ignoredException in `ConditionEvaluationResult`
- Rename trace to throwable (or exception?) in `IgnoredException`
Would you like me to do that?

**Comment by grofoli** [comment]
@johanhaleby I decided to rename `trace` to `throwable` only for the changes included in the present PR, since the trace in `ConditionEvaluationResult` is well documented on the constructor and according to that documentation the trace has a little bit more connotation than ignoredException. PR is updated by a second commit.

**Comment by johanhaleby** [comment]
@grofoli Thanks a lot! I think renaming trace to throwable is good enough. I'll merge the PR! :)

**Comment by johanhaleby** [comment]
@grofoli Since you've been helping so much lately, maybe you can give me some feedback on the thing I'm currently work on (waiting for exceptions)? I've written a comment here that I'd really appreciate some feedback on: https://github.com/awaitility/awaitility/issues/129#issuecomment-562513334

**Pull request merged**
