### PR TITLE
Un-ignored 1 OSGi-test by changing some dependency versions

### PR DESCRIPTION
**Pull request by ponziani**
- I was able to fix the first OSGi test by using an older version of the maven-surefire-plugin (I know from another project pax-exam doesn't go well with versions > 2.18) AND explicitly adding pax-swissbox-framework 1.8.3, whereas the transitive dependency would be 1.8.2. The latter could be left out once pax-exam 4.13 is released (I assume).
- I could not fix the proxy test, because apparently it was not enough to OSGify the proxy bundle. 
- The versions of felix and pax-exam can be bumped, everything kept working on my machine when I did.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Sorry for the late response, I've been away for a couple of days. Anyways, thanks a lot for the contribution. However I have one concern and that is this line: https://github.com/awaitility/awaitility/pull/118/files#diff-02f69497b44db38c74d5b77449e17ff7R11. Animal sniffer is used to detect lasses compiled with a newer JDK/API are compatible with an older JDK/API. Is this incompatible with OSGi? I'm reluctant to remove this plugin since it has caught some hard-to-detect bugs in the past.

**Comment by ponziani** [comment]
I dit not add that property, I think it's indentation was different before. The property was introduced in https://github.com/awaitility/awaitility/pull/90

**Comment by johanhaleby** [comment]
Oh sorry about that, need to investigate why it was ignored. Thanks again!

**Comment by ponziani** [comment]
No problem.

**Pull request merged**
