### PR TITLE
Use wall-clock agnostic System.nanoTime

### PR DESCRIPTION
**Pull request by barnardb**
As pointed out in #95, System.currentTimeMillis is sensitive to changes
in wall-clock time, such as when the user or NTP changes the system time.
This makes currentTimeMillis inapropriate for most timeout applications.
System.nanoTime, on the other hand, is wall-clock time agnostic.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Awesome, great contribution! From what I can see it's backward compatible as well?

**Comment by barnardb** [comment]
Yes, I tried to make it backward compatible.

**Comment by johanhaleby** [comment]
Thanks a lot for the pull request.

**Comment by barnardb** [comment]
NP. Thanks for the nice library :)

I'd love to get using this. Are you planning a release anytime soon?

**Comment by johanhaleby** [comment]
> I'd love to get using this. Are you planning a release anytime soon?

Yes ;)

**Pull request merged**
