### PR TITLE
Add bundle creation and OSGi test. Issue #59

### PR DESCRIPTION
**Pull request by cschneider**
I was successful in creating and testing the bundle. It is not fully compatible though as I had to remove the  shading to make it work.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Shading is used to repackage cglib into Awaitility to avoid conflicts and I'm reluctant to remove that. Why is shading not working?

**Comment by cschneider** [comment]
The shading works but bnd was creating the wrong meta data when the shading was active. I will ask on the osgi dev list how to get shading and bundle creation work together.

**Comment by johanhaleby** [comment]
thanks!

**Comment by cschneider** [comment]
I have now found a way to use both shading and bundle creation .. but I think cglib does not behave nicely in OSGi. It works when I export the embedded cglib packages. 

The pax exam test then sees them as pax exam uses dynamic import ... but the test classes should not need to see cglib.

**Comment by johanhaleby** [comment]
Cglib is only required when you use a java version prior to Java 8 and when you do stuff like:

```java
await().untilCall(to(someClass).methodName(), equalTo("X"));
```

I.e. when you create class proxies so I guess the use cases are quite limited nowadays. 

But if you think you got it working I'm all for merging the PR.

**Comment by cschneider** [comment]
I propose to try it like this and get feedback from users. I also plan to create some additional OSGi testing support in pax exam and intend to use awaitility there.

An interesting option mid term might be to split awaitility into a small package for java 8 without cglib. I noticed that cglib makes the jar quite a lot bigger.

**Comment by johanhaleby** [comment]
> An interesting option mid term might be to split awaitility into a small package for java 8 without cglib. I noticed that cglib makes the jar quite a lot bigger.

@cschneider Yeah, that's an interesting idea. I'll add that as an issue.

**Comment by johanhaleby** [comment]
Added issue here: https://github.com/awaitility/awaitility/issues/61

**Pull request merged**
