### PR TITLE
Hold condition during a period of time

### LINKED ISSUE #124: Testing a condition is maintained
Is there a way to test a condition is maintained for at least a given duration. To test condition A is maintained at least 5 seconds I have the following ugly code in my tests:

```
// do something in my test method
try {
    await().atMost(5, TimeUnit.SECONDS).until(this::testConditionA);
    assert false;
}catch (ConditionTimeoutException e){
    //nothing, everything is alright
}
// do something in my test method
```

Is there a better way to do the same thing ? Something I'd like to write would be:

`
await().atMost(5, TimeUnit.SECONDS).check(this::testConditionA);
`

### PR DESCRIPTION
**Pull request by padilo**
Allows to check if a condition is maintained during a period of time:

```
await().during(5, TimeUnit.SECONDS).until(this::testConditionA);
```
Check how It looks like the solution, not very happy with current implementation, but the idea is having a wait to tell the time the condition should hold.

A lot more of testing is also needed ;)

Closes  #124

### CODE REVIEW

**Comment by johanhaleby** [comment]
Hi Padilo! 

This is something that several people have asked for throughout the years so it would probably make for a good contribution. Thanks a lot! It would be great if you could add some more testing though so that we know that it really works :)

**Comment by padilo** [comment]
Sure, I work on testing this properly during this week. ;)

>

**Comment by padilo** [comment]
@johanhaleby Is it ok or there is some additional tests I should add?

**Comment by johanhaleby** [comment]
@padilo Thanks for pinging me, I was still waiting for you to add the tests but it turns out you've already done that several weeks ago. Sorry for missing this!

I think this is a cool addition. I'll bring it in!

**Pull request merged**
